server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: FacebookDB
      username: Java7User
      password: root
my-application:
  jwt:
    secret-key: "wr@M=dU4rur8splp0LvuPR_bEThutusT&q9ni3restaNlH-kOgab&wIFRobraspi"
    secret-key-env: ${SECRETKEY}